// include this file to build all of emilib except for iOS/Mac-specific stuff (.mm files).
#include "coroutine.cpp"
#include "dir_watcher.cpp"
#include "file_system.cpp"
#include "gl_lib.cpp"
#include "mem_map.cpp"
#include "movement_tracker.cpp"
#include "string_interning.cpp"
#include "strprintf.cpp"
#include "tga.cpp"
#include "timer.cpp"
#include "utf8.cpp"
#include "wav.cpp"
